/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.mvc.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.mvc.controller.customercontroller;
import pos.mvc.model.customermodel;

/**
 *
 * @author Hirushi
 */
public class customerview extends javax.swing.JFrame {

    /**
     * Creates new form customerview
     */
    private customercontroller Customercontroller;

    public customerview() {
        Customercontroller = new customercontroller();
        initComponents();
        loadAllCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerpanel = new javax.swing.JPanel();
        headerlabel = new javax.swing.JLabel();
        frompanel = new javax.swing.JPanel();
        customeridlabel = new javax.swing.JLabel();
        customeridtextfield = new javax.swing.JTextField();
        customertitlelabel = new javax.swing.JLabel();
        customertitletextfield = new javax.swing.JTextField();
        customernamelabel = new javax.swing.JLabel();
        customernametextfield = new javax.swing.JTextField();
        customerdoblabel = new javax.swing.JLabel();
        customerdobtextfield = new javax.swing.JTextField();
        customeraddresstextfield = new javax.swing.JTextField();
        customeraddresslabel = new javax.swing.JLabel();
        customercitylabel = new javax.swing.JLabel();
        customercitytextfield = new javax.swing.JTextField();
        customerprovincelabel = new javax.swing.JLabel();
        customerprovincetextfield = new javax.swing.JTextField();
        customerpostalcodelabel = new javax.swing.JLabel();
        customerpostalcodetextfield = new javax.swing.JTextField();
        deletecustomer = new javax.swing.JButton();
        addcustomer1 = new javax.swing.JButton();
        updatecustomer1 = new javax.swing.JButton();
        customerSALARYlabel = new javax.swing.JLabel();
        customersalarytextfield = new javax.swing.JTextField();
        tablepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customertable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setToolTipText("");

        headerpanel.setBackground(new java.awt.Color(255, 204, 255));

        headerlabel.setBackground(new java.awt.Color(255, 204, 255));
        headerlabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        headerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerlabel.setText("MANAGE CUSTOMER");

        javax.swing.GroupLayout headerpanelLayout = new javax.swing.GroupLayout(headerpanel);
        headerpanel.setLayout(headerpanelLayout);
        headerpanelLayout.setHorizontalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerpanelLayout.createSequentialGroup()
                .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerpanelLayout.setVerticalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        frompanel.setBackground(new java.awt.Color(255, 204, 204));

        customeridlabel.setBackground(new java.awt.Color(255, 204, 204));
        customeridlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customeridlabel.setText("Customer ID");
        customeridlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customertitlelabel.setBackground(new java.awt.Color(255, 204, 204));
        customertitlelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customertitlelabel.setText("Customer Title");
        customertitlelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customernamelabel.setBackground(new java.awt.Color(255, 204, 204));
        customernamelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customernamelabel.setText("Customer Name");
        customernamelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customerdoblabel.setBackground(new java.awt.Color(255, 204, 204));
        customerdoblabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerdoblabel.setText("Customer DOB");
        customerdoblabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customeraddresslabel.setBackground(new java.awt.Color(255, 204, 204));
        customeraddresslabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customeraddresslabel.setText("Customer Address");
        customeraddresslabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customercitylabel.setBackground(new java.awt.Color(255, 204, 204));
        customercitylabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customercitylabel.setText("Customer City");
        customercitylabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customerprovincelabel.setBackground(new java.awt.Color(255, 204, 204));
        customerprovincelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerprovincelabel.setText("Customer Province");
        customerprovincelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customerpostalcodelabel.setBackground(new java.awt.Color(255, 204, 204));
        customerpostalcodelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerpostalcodelabel.setText("Customer Postal Code");
        customerpostalcodelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deletecustomer.setBackground(new java.awt.Color(255, 204, 204));
        deletecustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletecustomer.setText("Delete Customer");
        deletecustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        deletecustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecustomerActionPerformed(evt);
            }
        });

        addcustomer1.setBackground(new java.awt.Color(255, 204, 204));
        addcustomer1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addcustomer1.setText("Save Customer");
        addcustomer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addcustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomer1ActionPerformed(evt);
            }
        });

        updatecustomer1.setBackground(new java.awt.Color(255, 204, 204));
        updatecustomer1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatecustomer1.setText("Update Customer");
        updatecustomer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updatecustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecustomer1ActionPerformed(evt);
            }
        });

        customerSALARYlabel.setBackground(new java.awt.Color(255, 204, 204));
        customerSALARYlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerSALARYlabel.setText("Customer Salary");
        customerSALARYlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout frompanelLayout = new javax.swing.GroupLayout(frompanel);
        frompanel.setLayout(frompanelLayout);
        frompanelLayout.setHorizontalGroup(
            frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frompanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customeridlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customertitlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerdoblabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customeraddresslabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customercitylabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerpostalcodelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerSALARYlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frompanelLayout.createSequentialGroup()
                        .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customertitletextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customeridtextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerdobtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(customernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(customernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(customeraddresstextfield)
                    .addGroup(frompanelLayout.createSequentialGroup()
                        .addComponent(customercitytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(customerprovincelabel)
                        .addGap(18, 18, 18)
                        .addComponent(customerprovincetextfield))
                    .addComponent(customerpostalcodetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customersalarytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frompanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatecustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addcustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        frompanelLayout.setVerticalGroup(
            frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frompanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customeridlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customeridtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customertitletextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customertitlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customernametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerdobtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerdoblabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customeraddresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customeraddresstextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customercitytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customercitylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerprovincelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerprovincetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerpostalcodetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerpostalcodelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customersalarytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerSALARYlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatecustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        tablepanel.setBackground(new java.awt.Color(255, 204, 204));

        customertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customertable);

        javax.swing.GroupLayout tablepanelLayout = new javax.swing.GroupLayout(tablepanel);
        tablepanel.setLayout(tablepanelLayout);
        tablepanelLayout.setHorizontalGroup(
            tablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        tablepanelLayout.setVerticalGroup(
            tablepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablepanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frompanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frompanel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addcustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomer1ActionPerformed
        saveCustomer();
    }//GEN-LAST:event_addcustomer1ActionPerformed

    private void customertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customertableMouseClicked
        searchCustomer();
    }//GEN-LAST:event_customertableMouseClicked

    private void updatecustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecustomer1ActionPerformed
        updateCustomer();
    }//GEN-LAST:event_updatecustomer1ActionPerformed

    private void deletecustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecustomerActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_deletecustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcustomer1;
    private javax.swing.JLabel customerSALARYlabel;
    private javax.swing.JLabel customeraddresslabel;
    private javax.swing.JTextField customeraddresstextfield;
    private javax.swing.JLabel customercitylabel;
    private javax.swing.JTextField customercitytextfield;
    private javax.swing.JLabel customerdoblabel;
    private javax.swing.JTextField customerdobtextfield;
    private javax.swing.JLabel customeridlabel;
    private javax.swing.JTextField customeridtextfield;
    private javax.swing.JLabel customernamelabel;
    private javax.swing.JTextField customernametextfield;
    private javax.swing.JLabel customerpostalcodelabel;
    private javax.swing.JTextField customerpostalcodetextfield;
    private javax.swing.JLabel customerprovincelabel;
    private javax.swing.JTextField customerprovincetextfield;
    private javax.swing.JTextField customersalarytextfield;
    private javax.swing.JTable customertable;
    private javax.swing.JLabel customertitlelabel;
    private javax.swing.JTextField customertitletextfield;
    private javax.swing.JButton deletecustomer;
    private javax.swing.JPanel frompanel;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tablepanel;
    private javax.swing.JButton updatecustomer1;
    // End of variables declaration//GEN-END:variables

    private void saveCustomer() {
        customermodel customer = new customermodel(
                customeridtextfield.getText(),
                customertitletextfield.getText(),
                customernametextfield.getText(),
                customerdobtextfield.getText(),
                Double.parseDouble(customersalarytextfield.getText()),
                customeraddresstextfield.getText(),
                customercitytextfield.getText(),
                customerprovincetextfield.getText(),
                customerpostalcodetextfield.getText());

        try {
            String resp = Customercontroller.saveCustomer(customer);
            JOptionPane.showConfirmDialog(this, resp);
            clear();
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    }

    public void clear() {
        customeridtextfield.setText("");
        customertitletextfield.setText("");
        customernametextfield.setText("");
        customeraddresstextfield.setText("");
        customerdobtextfield.setText("");
        customersalarytextfield.setText("");
        customercitytextfield.setText("");
        customerprovincetextfield.setText("");
        customerpostalcodetextfield.setText("");

    }

    private void loadAllCustomers() {
        try {
            String[] columns = {"Id", "Name", "Address", "Salary", "PostalCode"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }

            };

            customertable.setModel(dtm);

            ArrayList<customermodel> customers = Customercontroller.getAllCustomers();

            for (customermodel customer : customers) {
                Object[] rowData = {customer.getCustomerid(), customer.getCustomertitle() + " " + customer.getCustomername(), customer.getCustomeraddress() + "," + customer.getCustomercity(), customer.getCustomersalary(), customer.getCustmerpostalcode()};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    }

    public void searchCustomer() {
        try {
            String custId = customertable.getValueAt(customertable.getSelectedRow(), 0).toString();
            customermodel Customermodel = Customercontroller.getCustomer(custId);

            if (Customermodel != null) {

                customeridtextfield.setText(Customermodel.getCustomerid());
                customertitletextfield.setText(Customermodel.getCustomertitle());
                customernametextfield.setText(Customermodel.getCustomername());
                customeraddresstextfield.setText(Customermodel.getCustomeraddress());
                customerdobtextfield.setText(Customermodel.getCustomerdob());
                customersalarytextfield.setText(Double.toString(Customermodel.getCustomersalary()));
                customercitytextfield.setText(Customermodel.getCustomercity());
                customerprovincetextfield.setText(Customermodel.getCustomerprovince());
                customerpostalcodetextfield.setText(Customermodel.getCustomerpostalcode());
            }
            else{
                 JOptionPane.showConfirmDialog(this, "Customer not Fpund");
            }
        } catch (SQLException ex) {
            Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    }
    
    public void updateCustomer(){
        try {
            customermodel customer = new customermodel(
                    customeridtextfield.getText(),
                    customertitletextfield.getText(),
                    customernametextfield.getText(),
                    customerdobtextfield.getText(),
                    Double.parseDouble(customersalarytextfield.getText()),
                    customeraddresstextfield.getText(),
                    customercitytextfield.getText(),
                    customerprovincetextfield.getText(),
                    customerpostalcodetextfield.getText());
            
         String resp =   Customercontroller.updateCustomer(customer);
         JOptionPane.showConfirmDialog(this, resp);
            clear();
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void deleteCustomer(){
        try {
            String custID = customeridtextfield.getText();
            String resp = Customercontroller.deleteCustomer(custID);
            JOptionPane.showConfirmDialog(this, resp);
            clear();
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
