/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.mvc.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.mvc.controller.itemcontroller;
import pos.mvc.model.customermodel;
import pos.mvc.model.itemmodel;

/**
 *
 * @author Hirushi
 */
public class itemviwe extends javax.swing.JFrame {

    /**
     * Creates new form itemviwe
     */
    
    private itemcontroller Itemcontroller;
   
    public itemviwe() {
    Itemcontroller = new itemcontroller();
    initComponents();
    loadAllItem();  // Move the loadAllItem call here
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basepanel = new javax.swing.JPanel();
        titlepanel = new javax.swing.JPanel();
        titlelabel = new javax.swing.JLabel();
        formpanel = new javax.swing.JPanel();
        Item_code_label = new javax.swing.JLabel();
        item_code_textfield = new javax.swing.JTextField();
        description_label = new javax.swing.JLabel();
        description_textfield = new javax.swing.JTextField();
        packsize_label = new javax.swing.JLabel();
        packsize_textfield = new javax.swing.JTextField();
        unit_price_label = new javax.swing.JLabel();
        unitprize_textfield = new javax.swing.JTextField();
        qtyonhand_textfield = new javax.swing.JTextField();
        unit_price_label1 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlepanel.setBackground(new java.awt.Color(153, 255, 153));

        titlelabel.setBackground(new java.awt.Color(153, 255, 102));
        titlelabel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelabel.setText("ITEM MANAGE");

        formpanel.setBackground(new java.awt.Color(204, 255, 204));

        Item_code_label.setBackground(new java.awt.Color(204, 255, 204));
        Item_code_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Item_code_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item_code_label.setText("Item Code");
        Item_code_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        description_label.setBackground(new java.awt.Color(204, 255, 204));
        description_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        description_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description_label.setText("Discription");
        description_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        packsize_label.setBackground(new java.awt.Color(204, 255, 204));
        packsize_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        packsize_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        packsize_label.setText("Pack Size");
        packsize_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        unit_price_label.setBackground(new java.awt.Color(204, 255, 204));
        unit_price_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        unit_price_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unit_price_label.setText("Unit Price");
        unit_price_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        unit_price_label1.setBackground(new java.awt.Color(204, 255, 204));
        unit_price_label1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        unit_price_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unit_price_label1.setText("QnyOn Hand");
        unit_price_label1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        add_button.setBackground(new java.awt.Color(102, 255, 102));
        add_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_button.setText("Add Item");
        add_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        update_button.setBackground(new java.awt.Color(102, 255, 102));
        update_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update_button.setText("Update Item");
        update_button.setActionCommand("");
        update_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(102, 255, 102));
        delete_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delete_button.setText("Delete Item");
        delete_button.setActionCommand("");
        delete_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        itemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        itemtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemtable);

        javax.swing.GroupLayout formpanelLayout = new javax.swing.GroupLayout(formpanel);
        formpanel.setLayout(formpanelLayout);
        formpanelLayout.setHorizontalGroup(
            formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formpanelLayout.createSequentialGroup()
                        .addComponent(Item_code_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(item_code_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formpanelLayout.createSequentialGroup()
                        .addComponent(description_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(description_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formpanelLayout.createSequentialGroup()
                        .addComponent(packsize_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(packsize_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formpanelLayout.createSequentialGroup()
                        .addComponent(unit_price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(unitprize_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formpanelLayout.createSequentialGroup()
                        .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unit_price_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formpanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(qtyonhand_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formpanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(delete_button)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formpanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        formpanelLayout.setVerticalGroup(
            formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item_code_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_code_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(packsize_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packsize_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitprize_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtyonhand_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unit_price_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout titlepanelLayout = new javax.swing.GroupLayout(titlepanel);
        titlepanel.setLayout(titlepanelLayout);
        titlepanelLayout.setHorizontalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(formpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlepanelLayout.setVerticalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout basepanelLayout = new javax.swing.GroupLayout(basepanel);
        basepanel.setLayout(basepanelLayout);
        basepanelLayout.setHorizontalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        basepanelLayout.setVerticalGroup(
            basepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basepanelLayout.createSequentialGroup()
                .addComponent(titlepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        addItem();
    }//GEN-LAST:event_add_buttonActionPerformed

    private void itemtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemtableMouseClicked
        searchItem();
    }//GEN-LAST:event_itemtableMouseClicked

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        updateItem();
    }//GEN-LAST:event_update_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        deleteItem();
    }//GEN-LAST:event_delete_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Item_code_label;
    private javax.swing.JButton add_button;
    private javax.swing.JPanel basepanel;
    private javax.swing.JButton delete_button;
    private javax.swing.JLabel description_label;
    private javax.swing.JTextField description_textfield;
    private javax.swing.JPanel formpanel;
    private javax.swing.JTextField item_code_textfield;
    private javax.swing.JTable itemtable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel packsize_label;
    private javax.swing.JTextField packsize_textfield;
    private javax.swing.JTextField qtyonhand_textfield;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JPanel titlepanel;
    private javax.swing.JLabel unit_price_label;
    private javax.swing.JLabel unit_price_label1;
    private javax.swing.JTextField unitprize_textfield;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables

    private void addItem() {
    
          itemmodel Item = new itemmodel(
                  item_code_textfield.getText(), 
                  description_textfield.getText(), 
                  packsize_textfield.getText(),
                  unitprize_textfield.getText(),
                  qtyonhand_textfield.getText());
               

        try {
            String resp = Itemcontroller.addItem(Item);
            JOptionPane.showConfirmDialog(this, resp);
        } catch (SQLException ex) {
            Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
    }
}
    
     public void clear() {
        item_code_textfield.setText("");
        description_textfield.setText("");
        packsize_textfield.setText("");
        unitprize_textfield.setText("");
        qtyonhand_textfield.setText("");
        
    }

     private void loadAllItem() {
    try {
        String[] columns = {"Item Code", "Description", "Pack Size", "Unit Price", "Qty on Hand"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        itemtable.setModel(dtm);

        ArrayList<itemmodel> items = Itemcontroller.getAllItems();

        for (itemmodel item : items) {
            Object[] rowData = {
                item.getItem_Code(),
                item.getDescription(),
                item.getPacksize(),
                item.getUnitprice(),
                item.getQtyonhand()
            };
            dtm.addRow(rowData);
        }
    } catch (SQLException ex) {
        Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showConfirmDialog(this, ex.getMessage());
    }
}

public void searchItem() {
        try {
            String Itemcode = itemtable.getValueAt(itemtable.getSelectedRow(), 0).toString();
            itemmodel Itemmodel = Itemcontroller.getItem(Itemcode);

            if (Itemmodel != null) {

                item_code_textfield.setText(Itemmodel.getItem_Code());
                 description_textfield.setText(Itemmodel.getDescription());
                  packsize_textfield.setText(Itemmodel.getPacksize());
                   unitprize_textfield.setText(Itemmodel.getUnitprice());
                    qtyonhand_textfield.setText(Itemmodel.getQtyonhand());
                 
                
            }
            else{
                 JOptionPane.showConfirmDialog(this, "Item not Fpund");
            }
        } catch (SQLException ex) {
            Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    

}

 public void updateItem() {
    try {
        itemmodel item = new itemmodel(
                item_code_textfield.getText(),
                description_textfield.getText(),
                packsize_textfield.getText(),
                unitprize_textfield.getText(),
                qtyonhand_textfield.getText()
        );  // Add a semicolon here

        String resp = Itemcontroller.updateItem(item);
        JOptionPane.showConfirmDialog(this, resp);
        clear();
        loadAllItem();
    } catch (SQLException ex) {
        Logger.getLogger(customerview.class.getName()).log(Level.SEVERE, null, ex);
    }
}

   public void deleteItem(){
        try {
            String Itemcode = item_code_textfield.getText();
            String resp = Itemcontroller.deleteItem(Itemcode);
            
            JOptionPane.showConfirmDialog(this, resp);
            clear();
            loadAllItem();
        } catch (SQLException ex) {
            Logger.getLogger(itemviwe.class.getName()).log(Level.SEVERE, null, ex);
            
        }
   
   }
   
}
