/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.mvc.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pos.mvc.controller.customercontroller;
import pos.mvc.controller.ordercontroller;
import pos.mvc.controller.itemcontroller;
import pos.mvc.model.customermodel;
import pos.mvc.model.itemmodel;
import pos.mvc.model.orderdeailsmodel;
import pos.mvc.model.ordermodel;


/**
 *
 * @author Hirushi
 */
public class orderview extends javax.swing.JFrame {

    private customercontroller Customercontroller;
    private itemcontroller Itemcontroller;
    private ordercontroller Ordercontroller;
   
    
    ArrayList< orderdeailsmodel> orderdetails = new ArrayList<>();
    
    /**
     * Creates new form orderview
     */
    public orderview() {
        
        Customercontroller = new customercontroller();
        Itemcontroller = new itemcontroller();
        Ordercontroller=new ordercontroller();
        
        initComponents();
        loadOrderTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlepanel = new javax.swing.JPanel();
        titlelabel = new javax.swing.JLabel();
        formpanel = new javax.swing.JPanel();
        orderidlabel = new javax.swing.JLabel();
        orderidtextf = new javax.swing.JTextField();
        customerlabel = new javax.swing.JLabel();
        customertextf = new javax.swing.JTextField();
        customerbutton = new javax.swing.JButton();
        itemidlabel = new javax.swing.JLabel();
        itemidtextf = new javax.swing.JTextField();
        itemidbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        qtytextf = new javax.swing.JTextField();
        discountlabel = new javax.swing.JLabel();
        discounttextf = new javax.swing.JTextField();
        addorderbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        placeorderbutton = new javax.swing.JButton();
        customerdatalabel = new javax.swing.JLabel();
        itemIDdatalabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlepanel.setBackground(new java.awt.Color(0, 204, 255));

        titlelabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelabel.setText("ORDER MANAGE");

        javax.swing.GroupLayout titlepanelLayout = new javax.swing.GroupLayout(titlepanel);
        titlepanel.setLayout(titlepanelLayout);
        titlepanelLayout.setHorizontalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlepanelLayout.setVerticalGroup(
            titlepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        formpanel.setBackground(new java.awt.Color(0, 255, 255));

        orderidlabel.setText("Order ID");
        orderidlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customerlabel.setText("Customer");
        customerlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customerbutton.setBackground(new java.awt.Color(0, 204, 204));
        customerbutton.setText("Search");
        customerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerbuttonActionPerformed(evt);
            }
        });

        itemidlabel.setText("Item ID");
        itemidlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        itemidbutton.setBackground(new java.awt.Color(0, 204, 204));
        itemidbutton.setText("Search");
        itemidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemidbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("QTY");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        discountlabel.setText("Discount");
        discountlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addorderbutton.setBackground(new java.awt.Color(0, 204, 204));
        addorderbutton.setText("Add Order");
        addorderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorderbuttonActionPerformed(evt);
            }
        });

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ordertable);

        placeorderbutton.setBackground(new java.awt.Color(0, 153, 153));
        placeorderbutton.setText("Place Order");
        placeorderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeorderbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formpanelLayout = new javax.swing.GroupLayout(formpanel);
        formpanel.setLayout(formpanelLayout);
        formpanelLayout.setHorizontalGroup(
            formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formpanelLayout.createSequentialGroup()
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(discountlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemidlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(orderidlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderidtextf)
                    .addComponent(customertextf)
                    .addComponent(itemidtextf)
                    .addComponent(qtytextf, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(discounttextf, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formpanelLayout.createSequentialGroup()
                        .addComponent(customerbutton)
                        .addGap(18, 18, 18)
                        .addComponent(customerdatalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formpanelLayout.createSequentialGroup()
                        .addComponent(itemidbutton)
                        .addGap(18, 18, 18)
                        .addComponent(itemIDdatalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addorderbutton))
                .addGap(0, 49, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(placeorderbutton)
                .addGap(86, 86, 86))
        );
        formpanelLayout.setVerticalGroup(
            formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formpanelLayout.createSequentialGroup()
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(orderidtextf, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(orderidlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customertextf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerbutton)
                    .addComponent(customerdatalabel))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemidtextf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemidbutton)
                    .addComponent(itemIDdatalabel))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtytextf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discounttextf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addorderbutton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(placeorderbutton)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titlepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerbuttonActionPerformed
        searchCustomer();
    }//GEN-LAST:event_customerbuttonActionPerformed

    private void itemidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemidbuttonActionPerformed
        searchItem();
    }//GEN-LAST:event_itemidbuttonActionPerformed

    private void addorderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorderbuttonActionPerformed
        addOrder();
    }//GEN-LAST:event_addorderbuttonActionPerformed

    private void placeorderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeorderbuttonActionPerformed
        placeOrder();
    }//GEN-LAST:event_placeorderbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addorderbutton;
    private javax.swing.JButton customerbutton;
    private javax.swing.JLabel customerdatalabel;
    private javax.swing.JLabel customerlabel;
    private javax.swing.JTextField customertextf;
    private javax.swing.JLabel discountlabel;
    private javax.swing.JTextField discounttextf;
    private javax.swing.JPanel formpanel;
    private javax.swing.JLabel itemIDdatalabel;
    private javax.swing.JButton itemidbutton;
    private javax.swing.JLabel itemidlabel;
    private javax.swing.JTextField itemidtextf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderidlabel;
    private javax.swing.JTextField orderidtextf;
    private javax.swing.JTable ordertable;
    private javax.swing.JButton placeorderbutton;
    private javax.swing.JTextField qtytextf;
    private javax.swing.JLabel titlelabel;
    private javax.swing.JPanel titlepanel;
    // End of variables declaration//GEN-END:variables

    private void searchCustomer() {
        try {
            String custid = customertextf.getText();
            customermodel cust = Customercontroller.getCustomer(custid);
            
            if (cust != null) {
                customerdatalabel.setText(cust.getCustomername()+" "+cust.getCustomeraddress());
                
            } else {
                JOptionPane.showConfirmDialog(this, "Customer Not Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(orderview.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    }

    private void searchItem() {
        try {
            String itemid = itemidtextf.getText();
            itemmodel item = Itemcontroller.getItem(itemid);
            
            if (item != null) {
                itemIDdatalabel.setText(item.getDescription()+","+item.getPacksize()+","+item.getQtyonhand());
            } else {
                JOptionPane.showConfirmDialog(this, "Item Not Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(orderview.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
            clearForm();
        }
    }
    
    private void loadOrderTable(){
        String [] columns = {"ItemCode","Qty","Discount"};
        DefaultTableModel dm = new DefaultTableModel(columns, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return super.isCellEditable(row, column); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        };
        
        ordertable.setModel(dm);
    }

    private void addOrder() {
        orderdeailsmodel od = new orderdeailsmodel("", itemidtextf.getText(), qtytextf.getText(), discounttextf.getText());
        orderdetails.add(od);
        
        Object [] rowData = {od.getItemcode(),od.getOrderQty(),od.getDiscouunt()};
        DefaultTableModel dtm = (DefaultTableModel)ordertable.getModel();
        dtm.addRow(rowData);
        cleanOrderData();
        
         
    }

    private void cleanOrderData() {
        itemidtextf.setText("");
        discounttextf.setText("");
        qtytextf.setText("");
        itemIDdatalabel.setText("");
       
    }

    private void placeOrder() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-DD");
            ordermodel Ordermodel = new ordermodel(
                    orderidtextf.getText(),
                    sdf.format(new Date()),
                    customertextf.getText());
            
            String result = Ordercontroller.placeOrder(Ordermodel,orderdetails);
            JOptionPane.showConfirmDialog(this, result);
        } catch (SQLException ex) {
            Logger.getLogger(orderview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearForm() {
        loadOrderTable();
        orderidtextf.setText("");
        customertextf.setText("");
    }
    
   

}
